name: main

on:
  pull_request:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  publish:
    name: Publish package
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      packages: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: 'Setup pnpm'
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://npm.pkg.github.com'
          scope: '@polestar'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}

      - uses: ./.github/actions/publish
        with:
          github-token: ${{ github.token }}
          repository-url: ${{ github.repositoryUrl }}
